### ISSUE TITLE
叶间穿行 🌳Passable Foliage 🌳   https://www.mcmod.cn/class/3162.html

### ISSUE THREAD

**Issue by LiaoYK001** [ElemCraftInside-Server/.github#10]
叶间穿行 🌳Passable Foliage 🌳 https://www.mcmod.cn/class/3162.html

**Comment by rrrexfield** [comment]
有待测试，同时还需考虑该模组对游戏”特性“及可玩性的影响
![Image](https://github.com/ElemCraftInside-Server/.github/assets/125719548/e2620b11-1072-4d24-89ff-b516a90150bf)

**Comment by LiaoYK001** [comment]
树叶上不能站人了，有点不好，对于一些建造和特性不方便。现搁置 @yvisehrlohn @rrrexfield
