### ISSUE TITLE
[提案] 暮色森林 (Twilight Forest)

### ISSUE THREAD

**Issue by yvisehrlohn** [ElemCraftInside-Server/.github#49]
**暮色森林：**[CourseForge源](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/all?page=1&pageSize=20&version=1.20.1)
*附加模组：*[Twilight's Flavors & Delight (可以配合农夫乐事游玩)](https://www.curseforge.com/minecraft/mc-mods/twilights-flavors-delight/files/all?page=1&pageSize=20&version=1.20.1)

**本地测试没有模组冲突**

**Comment by LiaoYK001** [comment]
@rrrexfield
