### ISSUE TITLE
[提案] 机械动力拓展 New Age

### ISSUE THREAD

**Issue by yvisehrlohn** [ElemCraftInside-Server/.github#50]
*提供核反应堆，热气机等机械，产生源源不断的更强劲的动力*
[CourseForge源](https://www.curseforge.com/minecraft/mc-mods/create-new-age/files/all?page=1&pageSize=20&version=1.20.1)

**Comment by LiaoYK001** [comment]
@rrrexfield

**Comment by rrrexfield** [comment]
电力在机械动力中并没有太多应用场景，仅这个整合包的内容显得有点太少了。如果想玩电力的话，可以考虑加上[Create Crafts & Additions](https://www.mcmod.cn/class/3437.html)与其他使用电力的科技模组实现联动，如[通用机械](https://www.mcmod.cn/class/187.html)、[沉浸工程](https://www.mcmod.cn/class/463.html)、[应用能源2](https://www.mcmod.cn/class/260.html)等，但是这样整合包制作的工作量会大得可怕啊（瑟瑟发抖

**Comment by yvisehrlohn** [comment]
我确实想进一步提议加上这些模组，但现在还是先考虑稳定性吧
