### ISSUE TITLE
[DT]动态的树/有活力的树Dynamic Trees

### ISSUE THREAD

**Issue by LiaoYK001** [ElemCraftInside-Server/.github#59]
https://www.mcmod.cn/class/1071.html

**Comment by rrrexfield** [comment]
看评论，这个mod很吃性能啊，我们还要加那么多其他mod，这种纯装饰还吃性能的是不是可以pass？

**Comment by LiaoYK001** [comment]
> 看评论，这个mod很吃性能啊，我们还要加那么多其他mod，这种纯装饰还吃性能的是不是可以pass？

上周非上机商讨后已取消，过于破坏原版Minecraft方块属性
