### ISSUE TITLE
【真实地形+群系】Terratonic（数据包）『效果存疑』

### ISSUE THREAD

**Issue by LiaoYK001** [ElemCraftInside-Server/.github#61]
https://www.mcmod.cn/class/11751.html

**Comment by rrrexfield** [comment]
服务端没法用吧

**Comment by rrrexfield** [comment]
为什么不用reTerraforge🧐

**Comment by LiaoYK001** [comment]
这个是[【真实地形】Tectonic（mod或数据包）](https://github.com/ElemCraftInside-Server/.github/issues/58)和[【真实群系】Terralith（mod或数据包）](https://github.com/ElemCraftInside-Server/.github/issues/60)的整合版，风评不佳，仅做后续测试参考
