### ISSUE TITLE
在添加新模组时请记得考虑Mohist对模组的兼容性

### ISSUE THREAD

**Issue by rrrexfield** [ElemCraftInside-Server/.github#62]
**先讲结论：我们应该与早期整合包测试同步进行Mohist兼容性检查**
这个问题本应该在更早的时候提出来的，但是我前面忘记了，导致现在才想起来这个问题。
要注意Mohist作为一个混合服务端，并不保证对所有模组的兼容性。[详见Mohist官方文档](https://new.mohistmc.com/mohist/docs/versions)

![Image](https://github.com/ElemCraftInside-Server/.github/assets/125719548/07375d66-d575-4fcc-a7ee-a3118abff63e)

虽然1.20.1的Mod Compatibility为Good，但这并不代表其可以支持所有热门的、冷门的mod，etc.
引用Mohist官方的话，_The mod compatibility is good but there are still issues with them, but there are more compatible than plugins_.

![Image](https://github.com/ElemCraftInside-Server/.github/assets/125719548/c8daea58-f947-4c13-b287-1dd4ed8e6a9a)

所以我认为，在**进行早期整合包测试时就应该同步进行Mohist兼容性检查**，以避免客户端整合包配置好后在**服务端却不兼容导致的返工**。
值得注意的是，我所指的 _进行早期Mohist兼容性检查_ 并不是要求真的开一个服务端把Mod放进去看能否跑起来，而是在互联网上根据已有信息求证，我想这种方式应该能减小一些 _早期Mohist兼容性检查_ 的工作量。
@yvisehrlohn @LiaoYK001 **关联issue: #54**
_注：暂未发现将本issue翻译为英文的必要性_

**Comment by LiaoYK001** [comment]
收到，后续将从C2C联机测试改为使用[mohist最新版本](https://mohistmc.com/downloadSoftware?project=mohist&projectVersion=1.20.1)测试，测试时同步测试上表最新mohist。 @yvisehrlohn @rrrexfield
